name: Run Slack Schedule Bot

on:
  schedule:
    # Monday–Friday at 8:20 AM EST (12:20 UTC)
    - cron: '20 12 * * 1-5'
  workflow_dispatch:  # Allows manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run schedule bot
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: python daily_schedule.py
