name: Weekly Slack Reminder

on:
  schedule:
    # Runs every Thursday at 3:30 PM Eastern (which is 19:30 UTC during DST)
    - cron: '30 19 * * 4'
  workflow_dispatch:  # allows manual run from the Actions tab

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack_sdk

      - name: Send Slack reminder
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          python weekly_updates_reminder.py
